apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kcp-glbc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kcp-glbc
    app.kubernetes.io/part-of: kcp-glbc-app
  name: kcp-glbc
  namespace: kcp-glbc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kcp-glbc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kcp-glbc
    spec:
      containers:
      - image: quay.io/productcicd/hacbs-apps:kcp-glbc-dev-kcp-glbc
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
